spring:
  datasource:
    url: jdbc:mysql://localhost/mysql
    username: root
    password: root
    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      encoding: UTF-8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml