DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at DATE NOT NULL,
  updated_at DATE,
  del_flg BOOLEAN DEFAULT FALSE NOT NULL
);